spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vocab_ease?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    jwt:
      key: test123456
  application:
    name: VocabEase
    domain: "需配置域名"
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
server:
  port: 9091
project:
  folder: /www/VocabEase/
  #folder: D:/IdeaProject/VocabEase/
admin:
  phone: 13866668888
log:
  root:
    level: debug
isDev: false
mybatis:
  mapper-locations: classpath*:com/javastudy/vocabease_common/mappers/*.xml
  type-aliases-package: com.javastudy.vocabease_common.entity
  configuration:
    map-underscore-to-camel-case: true
ai:
  api-key: sk-e1d4f498aa1b4eadb87b1c37f195c31b